### ISSUE TITLE
使用插件后会导致玩家无法进入游戏

### ISSUE THREAD

**Issue by Colinwood11** [tocmic/deathPunishment#1]
复现版本V11   V12
服务器：LINUX
内容：
在检查的是否发现是您的插件的问题，查看了一下文件，发现在插件目录(plugins)中有个deathPunishment/log.bin文件
然后lang文件夹没有内容。反而出现在插件配置文件夹中(plugins/deathPunishment)有文件名字为lang/zh_cn.lang的文件。
大佬，您是不是目录什么的弄错了。
个人瞎几把猜测如下
配置文件存放错误位置，插件没有正确读取到，导致用户进入时无法正常加载。

其他补充：OP可以正常进入  玩家无法

**Comment by tocmic** [comment]
语言文件的地址是plugins/deathPunishment/lang没错，我没有修玩家登录事件，应该玩家登录的时候不会有任何反应。请问能不能提供一下你服务器的版本，以及玩家登录时后台的记录

**Comment by Colinwood11** [comment]
![image](https://user-images.githubusercontent.com/20866149/78269193-8bdea080-7509-11ea-9136-8a097b943be6.png)
![image](https://user-images.githubusercontent.com/20866149/78269231-9ac55300-7509-11ea-85fa-3c4fb0f586d6.png)
如图所示 我想说的是这两个文件的位置

**Comment by tocmic** [comment]
woc，你这里怎么回事，我怎么都复现不成这样的，你可以把\lang\xxx.lang前面的"\lang\"删掉后丢进lang文件夹里，然后把log.bin拿进deathPunishment这个文件夹就可以运行了。可能是系统的问题？我在winserver上面试验是不会出现这种情况的orz

**Comment by Colinwood11** [comment]
233333333  玄学？？？？？？？？   机器是CENTOS7的  换了一个CENTOS7的机器也一样。

**Comment by tocmic** [comment]
找到原因了，是因为俩系统的路径里的斜杠方向不一样！

**Comment by Colinwood11** [comment]
233333 等大佬解决后我再Close叭  虽然我服务器已经倒闭了
